#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <semaphore.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>

/*
void createAdult(int AWT, pid_t adultGen) {
    pid_t adult;
    int status;
    adult = fork();
    if (adult == 0) {
        printf("adult %d generated by %d\n", getpid(), getppid());
        int WT = rand() % (AWT + 1) * 1000;
        usleep(WT);
        exit(0);
    }else if (adult == -1){}
    else{
        adultGen = wait(&status);
        printf("adult %d finished.\n",adult);
    }
}
*/

int main(int argc, char **argv) {
    if (argc != 7){
        fprintf(stderr, "Neocekavane argumenty.\n");
        printf("%d",argc);
        return 1;
    }

    for (int i = 1; i < argc; i++) {
        for (int j = 0; argv[i][j] != '\0' ; j++) {
            if(argv[i][j] < '0' || argv[i][j] > '9' ){
                if(!(j == 0 && argv[i][j] == '-')) {
                    fprintf(stderr, "Neocekavane argumenty.\n");
                    return 1;
                }
            }
        }
    }

    int A = atoi(argv[1]);
    int C = atoi(argv[2]);
    int AGT = atoi(argv[3]);
    int CGT = atoi(argv[4]);
    int AWT = atoi(argv[5]);
    int CWT = atoi(argv[6]);

    pid_t adultGen,  adult, childGen, child;
    int i, status, AdultWT, AdultGT, ChildWT, ChildGT;
    srand(time(NULL));

    adultGen = fork();
    if(adultGen == 0){
        printf("adult generator %d\n", getpid());
        for(i = 1; i < A+1; i++){
            AdultGT = rand() % (AGT + 1) * 1000;
            usleep(AdultGT);
            adult = fork();
            if (adult == 0) {
                printf("A: A %d: started\n", i);
                printf("A: A %d: enter\n", i);
                AdultWT = rand() % (AWT + 1) * 1000;
                usleep(AdultWT);
                printf("A: A %d: trying to leave\n", i);
                exit(0);
            }else if (adult == -1){}
            else{
                adultGen = wait(&status);
                printf("A: A %d: leave.\n",i);
                printf("A: A %d: finished.\n",i);
            }
        }
        exit(0);
    }else if(adultGen == -1){}
    else{

    }


    childGen = fork();
    if(childGen == 0){
        printf("child generator %d\n", getpid());
        for(i = 1; i < C+1; i++){
            ChildGT = rand() % (CGT + 1) * 1000;
            usleep(ChildGT);
            child = fork();
            if (child == 0) {
                printf("C: C %d: started\n", i);
                printf("C: C %d: waiting\n", i);
                printf("C: C %d: enter\n", i);
                ChildWT = rand() % (CWT + 1) * 1000;
                usleep(ChildWT);
                printf("C: C %d: trying to leave\n", i);
                exit(0);
            }else if (child == -1){}
            else{
                childGen = wait(&status);
                printf("C: C %d: leave.\n",i);
                printf("C: C %d: finished.\n",i);
            }
        }
        exit(0);
    }

/*    childGen = fork();
    if(childGen == 0){
        printf("child generator%d\n", getpid());
        for(i = 0; i < C; i++){
            child = fork();
            if(child == 0){
                printf("child %d generated by %d\n", getpid(), getppid());
                WT = rand()%(CWT+1) * 1000;
                usleep(WT);
                exit(0);
            }
        }
    }

    for(j = 0; j < C; j++){
        child = wait(&status);
        printf("child %d finished.\n",child);
    }*/

    /*pid_t pid, child;
    int i, status;

    for(int i =  0; i< A; i++){
        pid = fork();
        if(pid == 0){
            printf("Running child %d under parrent %d\n",getpid(), getppid());
            pid = fork();
            if(pid == 0)
                printf("Running ch %d under child %d\n", getpid(), getppid());
            sleep(5);
            exit(0);
        }
    }

    for(i = 0; i < A; i++){
        child = wait(&status);
        printf("Child %d finished.\n",child);
    }*/
    //while(1);

    childGen = wait(&status);
    //adultGen = wait(&status);
        return 0;
}